/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 brain.gltf --transform
Files: brain.gltf [191.38KB] > /Users/shota/3Dmodel/hud_brain/brain-transformed.glb [164.45KB] (14%)
Author: tkkjee (https://sketchfab.com/tkkjee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hud-brain-25ed09ee28404810a009df6f4b3a5fda
Title: HUD Brain
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/brain-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} position={[0, 1.0, -0.4]} scale={0.408} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} position={[0, 1.0, -0.4]} scale={0.408} />
    </group>
  )
}

useGLTF.preload('/brain-transformed.glb')
