/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 gamecon.gltf --transform
Files: gamecon.gltf [272.01KB] > /Users/shota/3Dmodel/xe-1st2/gamecon-transformed.glb [114.88KB] (58%)
Author: mr.mak3r99 (https://sketchfab.com/mak3r99)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xe-1st2-b4e82b54531340be9cc8ada35a97b5b9
Title: XE-1ST2
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/gamecon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0.3, 0.186, -0.452]} scale={[0.12, 0.2225, 0.12]} />
    </group>
  )
}

useGLTF.preload('/gamecon-transformed.glb')
