/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 meta.gltf --transform
Files: meta.gltf [50.72MB] > /Users/shota/3Dmodel/meta_quest_3_low_poly_oculus_quest/meta-transformed.glb [945.95KB] (98%)
Author: Alvin Suen (https://sketchfab.com/alvinwcsuen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/meta-quest-3-low-poly-oculus-quest-f9292d0388d7447f865fefb667b86085
Title: Meta Quest 3 Low Poly (Oculus Quest)
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/meta-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.buttons_L_low_meta_quest_3_mat_0.geometry} material={materials.meta_quest_3_mat} position={[0, 0, 0]} rotation={[0.381, 0.285, 0.016]} scale={0.041} />
    </group>
    //
  )
}

useGLTF.preload('/meta-transformed.glb')
