/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 robot.gltf --transform
Files: robot.gltf [63.82MB] > /Users/shota/robot__2020/robot-transformed.glb [819.21KB] (99%)
Author: Uliszs.3d (https://sketchfab.com/uliszs.3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-2020-c0dadae4d1884bf48615f1ee301fe7e6
Title: Robot | 2020
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/robot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CHARACTER__0.geometry} material={materials['Scene_-_Root']} position={[0, 2.656, -11]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/robot-transformed.glb')
